### ISSUE TITLE
Missing Files in Final Folder

### ISSUE THREAD

**Issue by ExpiredCoder** [timsutton/brigadier#102]
I have installed Tiny11 on my MacBookPro11,2 a few days ago. I needed windows drivers for my apple hardware but i can not find any. I have tried using brigadier but there is an error where nothing shows up in the folder. I checked the temp folder but the files that I needed were not there.

​

C:\Users\Cameron\Downloads>C:\Users\Cameron\Downloads\brigadier.exe -m MacBookPro11,2

Using Mac model: MacBookPro11,2.

​

Model supported in package distribution file at https://swdist.apple.com/content/downloads/62/58/041-98143-A_HN8B941A1T/nknv1gt3xcgylggwc11kl5e0j4296tjfo1/041-98143.English.dist.

​

Distribution [041-98143](tel:041-98143) supports the following models: MacBook8,1, MacBookAir5,1, MacBookAir5,2, MacBookAir6,1, MacBookAir6,2, MacBookAir7,1, MacBookAir7,2, MacBookPro9,1, MacBookPro9,2, MacBookPro11,1, MacBookPro11,2, MacBookPro11,3, MacBookPro11,4, MacBookPro11,5, MacBookPro12,1, MacPro6,1, Macmini6,1, Macmini6,2, Macmini7,1, iMac13,1, iMac13,2, iMac13,3, iMac14,1, iMac14,2, iMac14,3, iMac14,4, iMac15,1.

​

Final output path C:\Users\Cameron\Downloads\BootCamp-041-98143 already exists, removing it...

​

Making directory C:\Users\Cameron\Downloads\BootCamp-041-98143..

​

Fetching Boot Camp product at URL http://swcdn.apple.com/content/downloads/62/58/041-98143-A_HN8B941A1T/nknv1gt3xcgylggwc11kl5e0j4296tjfo1/BootCampESD.pkg.

​

100.0% [1614471168](tel:1614471168) / [1614464893](tel:1614464893) bytes

Extracting...

​

Calling 7-Zip command: C:\Program Files\7-Zip\7z.exe e -oc:\users\cameron\appdata\local\temp\bootcamp-unpack_argngr -y c:\users\cameron\appdata\local\temp\bootcamp-unpack_argngr\BootCampESD.pkg

​

​

7-Zip 23.01 (x64) : Copyright (c) 1999-2023 Igor Pavlov : 2023-06-20

​

Scanning the drive for archives:

1 file, [1614464893](tel:1614464893) bytes (1540 MiB)

​

Extracting archive: c:\users\cameron\appdata\local\temp\bootcamp-unpack_argngr\BootCampESD.pkg

--

Path = c:\users\cameron\appdata\local\temp\bootcamp-unpack_argngr\BootCampESD.pkg

Type = Xar

Physical Size = [1614464893](tel:1614464893)

SubType = pkg

Headers Size = 4209

----

Path = Payload

Size = [1614449168](tel:1614449168)

Packed Size = [1614449168](tel:1614449168)

Modified = 2016-03-31 13:21:12.0000000

Created = 2016-03-31 13:21:32.0000000

Accessed = 2016-03-31 13:15:12.0000000

Mode = -rw-r--r--

User = root

Group = wheel

Method = octet-stream

--

Path = Payload

Type = bzip2

​

Everything is Ok

​

Size: [1613847552](tel:1613847552)

Compressed: 1614464893

Calling 7-Zip command: C:\Program Files\7-Zip\7z.exe e -oc:\users\cameron\appdata\local\temp\bootcamp-unpack_argngr -y c:\users\cameron\appdata\local\temp\bootcamp-unpack_argngr\Payload~

​

​

7-Zip 23.01 (x64) : Copyright (c) 1999-2023 Igor Pavlov : 2023-06-20

​

Scanning the drive for archives:

1 file, [1613847552](tel:1613847552) bytes (1540 MiB)

​

Extracting archive: c:\users\cameron\appdata\local\temp\bootcamp-unpack_argngr\Payload~

​

WARNINGS:

There are data after the end of archive

​

--

Path = c:\users\cameron\appdata\local\temp\bootcamp-unpack_argngr\Payload~

Type = Cab

WARNINGS:

There are data after the end of archive

Offset = 2177233

Physical Size = 794777

Tail Size = [1610875542](tel:1610875542)

Method = MSZip

Blocks = 1

Volumes = 1

Volume Index = 0

ID = 0

​

ERROR: Data Error : [Windows6.1-KB2685811-x64.cab](https://windows6.1-kb2685811-x64.cab/)

ERROR: Data Error : Windows6.1-KB2685811-x64-pkgProperties.txt

ERROR: Data Error : Windows6.1-KB2685811-x64.xml

​

Sub items Errors: 3

​

Archives with Errors: 1

​

Warnings: 1

​

Sub items Errors: 3

Command failure: C:\Program Files\7-Zip\7z.exe e -oc:\users\cameron\appdata\local\temp\bootcamp-unpack_argngr -y c:\users\cameron\appdata\local\temp\bootcamp-unpack_argngr\Payload~ exited 2.

**Comment by HeckFinlay** [comment]
A potential workaround:

1. Download `BootCampESD.pkg` directly from the URL in the Brigadier output.
2. Unpack it on a Mac by opening it and clicking through the installer.*
3. Mount the resulting `/Library/Application Support/BootCamp/WindowsSupport.dmg` and copy the contents to the Windows installation.
4. Run the included `setup.exe` to install the BootCamp drivers.

*It may also be possible to unpack the .pkg file manually with the 7-Zip GUI or command line switches.

**Comment by Ian2209** [comment]
I have exactly the same issue with iMac14,2 on Windows 11. As I do not have a regular mac, I cannot use the workaround mentioned above. Tried everything else, but always get the same extract data error.

ERROR: Data Error : Windows6.1-KB2685811-x64.cab
ERROR: Data Error : Windows6.1-KB2685811-x64-pkgProperties.txt
ERROR: Data Error : Windows6.1-KB2685811-x64.xml

Sub items Errors: 3

Archives with Errors: 1

Warnings: 1

Sub items Errors: 3
Command failure: C:\Program Files\7-Zip\7z.exe e -oc:\users\iossher\appdata\local\temp\bootcamp-unpack_ug2vao -y c:\users\iossher\appdata\local\temp\bootcamp-unpack_ug2vao\Payload~ exited 2.

**Comment by ExpiredCoder** [comment]
@HeckFinlay 
Should a VM with macOS work with unpackaging the file?

**Comment by ldannewitz** [comment]
I was experiencing the same thing. I think it's the 7-Zip version, see [this thread](https://github.com/timsutton/brigadier/issues/94). Once I switched from 7-Zip 23.01 to 7-Zip 22.01 I was at least able to pull the files, but the driver still didn't work to enable scrolling :(

**Comment by ExpiredCoder** [comment]
@ldannewitz thats what I did and it worked, if you are using Mac trackpad, make sure it is the right computer drivers. If it is and Apple Magic Mouse, use Apple Update Software that should be installed with the drivers. After a while of installing the drivers,  some boot camp and Magic Mouse drivers appeared, make sure to regularly check the update software for updates.
