### ISSUE TITLE
Support for installation on 32-bit Windows

### ISSUE THREAD

**Issue by timsutton** [timsutton/brigadier#2]
Tracking interest in supporting 32-bit Windows with the `--install` option. The latest ESD for iMac13 and Macmini6 is 64-bit only, worth noting.

**Comment by bowerymarc** [comment]
rats! just found this page and have a macbook pro 2,2 trying to install win7 32 bit (not enough memory for 64b), and I see the issue was closed 2 years ago :(

**Comment by timsutton** [comment]
Sorry, given that Apple's now been doing 64-bit only for a few years, supporting 32-bit would be a bunch of extra cases to add for which I can even easily test.
