### ISSUE TITLE
Desperately -need -an -uninstall -option 

### ISSUE THREAD

**Issue by robdavis95** [timsutton/brigadier#21]
(dodgy text incoming, apologies)

I -installed -the -driv#er -in -a -hope -to -fix -my -mac] -keyboard -on -my -windows -PC.8 -Sinc]e -then -I -had -resolv#ed -the -issue.8 -I -had -followed -this -tutorial [https://www.youtube.com/watch?v=A8_4pPs-l38](https://www.youtube.com/watch?v=A8_4pPs-l38)

(As -you -c]an -see )  -it's -mapped -all -of -the -keys -inc]orrec]tly -now -and -I -c]annot -uninstall -the -driv#er.8 -

The -keyboard -works -fine -on -my -Mac]book -Pro 2015 -so -it -is -definitely -the -driv#er that -is -c]ausing -these -issues.8 

Any -help -would -be -greatly -apprec]iated. -I -don't -want -to -spend -money on -another  -keyboard -or -reformat -my -OS

Remapped keys:
Space -->  -
c --> c]
v --> v#
, --> ,7
. --> 8
7 --> ,7
8 --> .8
There -may -be -some -others -but -I hav#en't -found -them -yet.8

**Comment by Ohaaa** [comment]
Hey!

Just answered this question in another thread. Maybe this helps:
[https://github.com/timsutton/brigadier/issues/20#issuecomment-242356457](url)

**Comment by robdavis95** [comment]
Thank you for the help, in the end I had to reformat my PC. A bit of a pain but it worked.

Hopefully this advice can helps others in the same situation though.
