### ISSUE TITLE
Unable to install bootcamp for MacPro5,1

### ISSUE THREAD

**Issue by misanthrophy** [timsutton/brigadier#35]
Hello,

I followed a guide for installing the drivers for my MacPro5,1 from here:

https://forums.macrumors.com/threads/how-to-boot-camp-without-a-boot-screen.2114788/page-9#post-26689280

My Problem is with that part:

14) Open Command Prompt (search CMD can find it)

15) type
Code:
e:
16) type
Code:
brigadier -m MacPro5,1
17) Once finished, rename the "Bootcampxxxxxxxxxx" folder to "Bootcamp5"

20) search CMD again, but this time right click, and choose "run as admin"

21) type
Code:
e:
22) type
Code:
cd Bootcamp5/Bootcamp/Drivers/Apple
23) type
Code:
msiexec /i bootcamp.msi 

When I try to execute that command, it says, I need to install windows 7, even though I have windows 10 1803 version installed. 

I tried it several times. Is there an issue with the downloaded files or how can I fix that issue?

Thx in advance

**Comment by iVibes** [comment]
Download the latest Brigadier.exe executable file, copy to desktop and run that as administrator. 

Once the script has worked it magic and you get a Bootcamp folder on desktop there’s no need to rename any folders. Run the setup file within the Apple folder from within Explorer.

If the same error message occurs right click the installer file and select properties and use compatibility mode to change versions to Windows 7.
