### ISSUE TITLE
Error- Couldn't find a Boot Camp ESD for the model Precision 5520

### ISSUE THREAD

**Issue by Debugger28** [timsutton/brigadier#36]
I am getting this error.

Platform- Windows 10 64

H:\>brigadier.exe
Using Mac model: Precision 5520.

Couldn't find a Boot Camp ESD for the model Precision 5520 in the given software update catalog.

**Comment by iVibes** [comment]
This tool is only designed to be run on genuine Macs running Windows via Bootcamp.

Dell Precision 5520’s do not qualify.

**Comment by Jihxn** [comment]
Couldn't find a Boot Camp ESD for the model Macbook9,1 in the given software update catalog.

running: macOS Bigsur
