### ISSUE TITLE
New iMac models are not supported

### ISSUE THREAD

**Issue by muHashh** [timsutton/brigadier#59]
when running either `.\brigadier.exe -m "iMac21,2"` or `.\brigadier.exe -m "iMac21,1"`, I get `Couldn't find a Boot Camp ESD for the model iMac21,2 in the given software update catalog`.

**Comment by timsutton** [comment]
This is because new iMacs are Apple Silicon architecture, and Boot Camp is not supported on these models at all (and won't be as far as we know).

I'll close this but opened https://github.com/timsutton/brigadier/issues/60 if we can make the output more instructive.
