### ISSUE TITLE
Windows defender sees zip file as trojan malware

### ISSUE THREAD

**Issue by juleast** [timsutton/brigadier#77]
WinDefender seems to think the zip file from the release to be a Trojan:Script/Sabsik.FL.A!ml . Is this a false positive or has something happened? 
![image](https://user-images.githubusercontent.com/44688633/201810121-aebe6c5a-8404-41da-a283-ef6428f970a5.png)

(I put some annotated translations as my Windows is not in English)

**Comment by ExpiredCoder** [comment]
This is just windows trying to be secure. You can allow it and if it still does not run, then disable real-time protection in the defender settings. After that try to run it.
