### ISSUE TITLE
Not a real issue just wondering...

### ISSUE THREAD

**Issue by BaddMann** [timsutton/brigadier#8]
Your last release listed the catalog for Mavericks as an update.

That was a while back, can we update to Yosemite now or is it too soon?

**Comment by timsutton** [comment]
You can certainly use the Yosemite catalog, and the next release will include this as the default. Most likely you'd need this for the 5K iMac and 2014 Mac Minis.

In the meantime you can specify the URL you'd like using the plist option as detailed in the readme and [here](https://github.com/timsutton/brigadier/blob/master/plist-example/brigadier.plist).
