### ISSUE TITLE
i have installed wrong bootcamp pack and gettin error

### ISSUE THREAD

**Issue by vvvvvvvvvvvvvvvvvvv2** [timsutton/brigadier#95]
ERROR: Data Error : Windows6.1-KB2685811-x64.cab
ERROR: Data Error : Windows6.1-KB2685811-x64-pkgProperties.txt
ERROR: Data Error : Windows6.1-KB2685811-x64.xml

Command failure: C:\Program Files\7-Zip\7z.exe e -oc:\users\****\appdata\local\temp\bootcamp-unpack_znkum7 -y c:\users\****\appdata\local\temp\bootcamp-unpack_znkum7\Payload~ exited 2.

i deleted everything in temp folder but this doesnt help me.
error produce while i trying install right bootcamp pack

**Comment by vvvvvvvvvvvvvvvvvvv2** [comment]
anyone?

**Comment by JonnyTech** [comment]
Reinstall Windows

**Comment by vvvvvvvvvvvvvvvvvvv2** [comment]
> Reinstall Windows

cant do that. at all. i forgot firmware pass

**Comment by JonnyTech** [comment]
Reset Windows ("Reset this PC")
